name: gsv-bias-scraper
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - folium
  - tqdm
  - matplotlib
  - pandas
  - httpx
  - tenacity
  - nest_asyncio
variables:
  API_KEY: "AIzaSyAKPZf-Z4LNIOTan3XrTD-WPrdXPNddGnI"