name: gsv-bias-venv
channels:
  - default
  - conda-forge
dependencies:
  - numpy=1.26.0
  - folium=0.14.0
  - tqdm=4.66.1
  - matplotlib=3.8.0
  - pandas=2.1.1
  - httpx=0.25.0
  - tenacity=8.2.3
  - nest-asyncio=1.5.8 
  - geopy=2.4.0

